// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl7TcccMTo92NxbqaYirha6ltQM3K1lFk',
    appId: '1:675767268007:web:c51dc1c7e5b0a219a1a182',
    messagingSenderId: '675767268007',
    projectId: 'visa-arapiraca',
    authDomain: 'visa-arapiraca.firebaseapp.com',
    storageBucket: 'visa-arapiraca.firebasestorage.app',
    measurementId: 'G-SDFLF3YRBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGU8O1d8CCxTel8ZmkzzqTrakzTCU90fQ',
    appId: '1:675767268007:android:4ece9d5a5417f34fa1a182',
    messagingSenderId: '675767268007',
    projectId: 'visa-arapiraca',
    storageBucket: 'visa-arapiraca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzFAmDO3BNqXR4WqXYPPxoLAaXb5UKleM',
    appId: '1:675767268007:ios:bdf3cffc2e7e5beaa1a182',
    messagingSenderId: '675767268007',
    projectId: 'visa-arapiraca',
    storageBucket: 'visa-arapiraca.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzFAmDO3BNqXR4WqXYPPxoLAaXb5UKleM',
    appId: '1:675767268007:ios:bdf3cffc2e7e5beaa1a182',
    messagingSenderId: '675767268007',
    projectId: 'visa-arapiraca',
    storageBucket: 'visa-arapiraca.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl7TcccMTo92NxbqaYirha6ltQM3K1lFk',
    appId: '1:675767268007:web:dde855e9eaf1c3bba1a182',
    messagingSenderId: '675767268007',
    projectId: 'visa-arapiraca',
    authDomain: 'visa-arapiraca.firebaseapp.com',
    storageBucket: 'visa-arapiraca.firebasestorage.app',
    measurementId: 'G-N2GLLERZMV',
  );
}
